### ISSUE TITLE
Subfolder direction not working

### ISSUE THREAD

**Issue by bitwolfe** [SEDAdigital/XRouting#1]
For some reason I couldn't get the subfolder feature working. We had used the Gateway plugin before, but decided to switch to XRouting now that this better option is available. I had set up three contexts out of which two are on one domain with different base_urls and the third on it's own domain.

```
web:
    base_url: /
    cultureKey: fi
    http_host: www.exampledomain.fi
    site_url: http://www.exampledomain.fi/

swe:
    base_url: /sv/
    cultureKey: sv
    http_host: www.exampledomain.fi
    site_url: http://www.exampledomain.fi/sv/

se:
    base_url: /
    cultureKey: sv
    http_host: www.exampledomain.se
    site_url: http://www.exampledomain.se
```

With the above setup the two domains with root base_url worked perfectly, but the subfolder was ignored and returned the web context instead. Maybe I missed something?

We resorted to putting the swe context on a subdomain instead, which works, but since this is a feature I assume this is either a bug or fail on my part.
