### ISSUE TITLE
Routing not working

### ISSUE THREAD

**Issue by bitwolfe** [SEDAdigital/XRouting#7]
I cannot get this plugin to work, bu I'm probably missing something.

I've set up my contexts as 

```
web:
    http_host: example.com
    base_url: /
ajax:
    http_host: example.com
    base_url: /ajax/
```

I've tried debugging it and it correctly switches to the ajax context, but it then runs a second request, which instead returns the web context. It cannot find a match against ajax anymore because the request url has changed.

I tried commenting out the request url changes after the context switch, which stopped it from running a second request matching, but it still doesn't work. I always get sent to the error page.

I have also set the appropriate site_start settings on both contexts. Didn't make a difference however.

Any ideas?
